version: '3.8'
services: 
  api:
    container_name: backend-container
    restart: always
    build: .
    ports: 
      - "8081:3000"
    depends_on: 
      - mongo

  mongo:
    container_name: mongo-backend
    image: mongo
    expose: 
      - "27017"
    ports: 
      - "27017:27017"
    volumes: 
      - apiDB:/data/db

volumes: 
  apiDB: